/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aspire.interview;

import java.sql.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }





    public static void main(String[] args) throws SQLException {
        String s1= "THis & * 12345678z_k ";
        Logic2 logic2=new Logic2();
        logic2.countNumberAndSpaceAndString(s1);
//        String[]arr={"Apple","Banana","Cucumber","Watermelon","Ice-cream","Orange","Eggplant","Egg"};
//        Logic1 logic1=new Logic1();
//        logic1.startWithAEIOU(arr);
//        logic1.nameLongerThanFive(arr);
//        SqlTest sqltest=new SqlTest();
//        System.out.println(sqltest.numOfProduct());
//        System.out.println(sqltest.numOfProductLessThanFive());
//        System.out.println(sqltest.leastExpensiveProduct());

    }
}
